<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZ8nABr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZ8nABr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZ8nABr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZ8nABr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZ8nABr\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZ8nABr',
    'container.build_id' => 'b56c2d45',
    'container.build_time' => 1684699755,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZ8nABr');
