<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRubC4LY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRubC4LY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRubC4LY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRubC4LY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRubC4LY\App_KernelDevDebugContainer([
    'container.build_hash' => 'RubC4LY',
    'container.build_id' => 'c3a7fc4a',
    'container.build_time' => 1684879048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRubC4LY');
